[application]

# App (Project) Name
name = "rust-fullstack"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "./dist"

# resource (public) file folder
asset_dir = "public"

# base_path = "."

[web.app]

# HTML title tag content
title = "dioxus | ⛺"
# base_path = "."

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = false

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# uncomment line below if using Router
index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# serve: [dev-server] only

# CSS style file
style = []
# style = ["tailwind.css"]


# Javascript code file
script = [
"https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js",
"https://cdn.jsdelivr.net/npm/echarts-gl@2.0.9/dist/echarts-gl.min.js"
]